# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ACI Security Summit
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

speakers:
  - logo: 'belgium-government-logo-400x210.png'
    name: Jan Jambon
    title: Belgian Vice-Prime Minister
    company: and Security & Interior Minister
  - logo: 'schiphol-logo-400x210.png'
    name: Bart Mos
    title: Senior Security Officer
    company: Amsterdam Airport Schiphol
  - logo: 'european-comission-400x210.png'
    name: Henrik Hololei
    title: Director General DG Move
    company: European Commission
  - logo: 'tsa-logo-400x210.png'
    name: Huban A. Gowadia
    title: Deputy Administrator
    company: TSA
  - logo: 'department-for-transport-uk-400x210.png'
    name: Phil Dykins
    title: Head of Aviation Security Policy
    company: Department for Transport (DfT), United Kingdom
  - logo: 'brussels-airport-400x210.png'
    name: Wilfried Covent
    title: Head of Security
    company: Brussels Airport
  - logo: 'fraport-logo-400x210.png'
    name: Philipp Kriegbaum
    title: Vice President, Security and Quality Management
    company: Fraport
  - logo: 'blake-emergency-services-267x140.png'
    name: Abigail Pollard
    title: Managing Director
    company: Blake Emergency Services
  - logo: 'heathrow-logo-400x210.png'
    name: Alexis Long
    title: Head of Security Policy
    company: Heathrow Airport
  - logo: 'swedavia-logo-400x210.png'
    name: Mats Paulsson
    title: Senior Security Coordinator
    company: Swedavia

exhibitors:
  - logo: 'atos-logo-400x210.png'
    name: Atos
    stand: F3
    category: unknown
    link:
  - logo: 'dsa-detection-logo-400x210.jpg'
    name: DSA Detection
    stand: F9
    category: unknown
    link:
  - logo: 'l3-security-detection-systems-400x210.png'
    name: L3 Security
    stand: F11
    category: unknown
    link:
  - logo: 'everbridge-logo-400x210.png'
    name: Everbridge
    stand: F13
    category: unknown
    link:
  - logo: 'csa-international-logo-400x210.png'
    name: CS&A International
    stand: F23
    category: unknown
    link:
  - logo: 'smiths-detection-400x210.png'
    name: Smiths Detection
    stand: F27
    category: unknown
    link:


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - source
   - gulpfile.js
   - gitignore
   - package.json
   - package-lock.json
   - package.lock
   - server
